name: genes2genes-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - anndata
  - regex
  - textdistance
  - tabulate
  - gseapy
  - gprofiler-official
  - seaborn
  - levenshtein
  - pytorch
  - gpytorch
  - scanpy
  - adjusttext
  - ipympl