name: genes2genes-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - ipykernel
  - anndata
  - regex
  - textdistance
  - tabulate
  - gseapy
  - gsea-api
  - gprofiler-official
  - seaborn
  - levenshtein
  - torch
  - pytorch
  - gpytorch
  - scanpy
  - adjusttext
  - ipympl
  - python=3.8
  - colorcet
  - optbinning
  - scipy
  - tqdm
  - sklearn
  - matplotlib
  - pandas
  - leven
  - multiprocessing
  - copy
  - warnings
  - pickle
  - mpl_toolkits